# SAMSHA MH-CLD

## Environment

In [1]:
# setting the random seed for reproducibility
import random
random.seed(493)

import os

# for manipulating dataframes
import pandas as pd

In [2]:
# to print out all the outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

## Data Acquisition and Wrangling

In [3]:
# Define the folder path
folder_path = '../data/csv'

# Loop through the years and create DataFrames dynamically
for year in range(2020, 2023):  # From 2020 to 2022 inclusive
    file_name = f'mhcld_puf_{year}.csv'
    file_path = os.path.join(folder_path, file_name)
    
    # Read the CSV file into a DataFrame
    df = pd.read_csv(file_path)
    
    # Dynamically assign the DataFrame to a variable name
    globals()[f'df_{year}'] = df

In [4]:
for year in range(2020, 2023):  # From 2020 to 2022 inclusive
    df_name = f'df_{year}'
    if df_name in globals():  # Check if the DataFrame exists
        print(f"Head of {df_name}:")
        globals()[df_name].head()

Head of df_2020:

,YEAR,AGE,EDUC,ETHNIC,RACE,GENDER,SPHSERVICE,CMPSERVICE,OPISERVICE,RTCSERVICE,IJSSERVICE,MH1,MH2,MH3,SUB,MARSTAT,SMISED,SAP,EMPLOY,DETNLF,VETERAN,LIVARAG,NUMMHS,TRAUSTREFLG,ANXIETYFLG,ADHDFLG,CONDUCTFLG,DELIRDEMFLG,BIPOLARFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
0,2020,14,-9,4,3,1,1,1,1,2,2,5,11,-9,-9,1,1,1,-9,-9,-9,3,2,0,0,0,0,1,0,0,0,0,0,1,0,0,1,6,3,20200000001
1,2020,1,2,4,1,1,2,1,2,2,2,13,2,3,-9,1,2,2,-9,-9,-9,-9,3,0,1,1,0,0,0,0,0,0,0,0,0,1,1,6,3,20200000002
2,2020,3,3,4,6,2,2,1,2,1,2,1,2,-9,-9,-9,2,2,5,5,-9,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0,1,6,3,20200000003
3,2020,12,4,4,1,1,1,1,2,2,2,11,10,-9,5,-9,1,1,2,-9,-9,3,2,0,0,0,0,0,0,0,0,0,1,1,0,0,1,6,3,20200000004
4,2020,8,3,3,5,1,2,1,1,2,2,10,-9,-9,10,-9,1,1,1,-9,-9,3,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,6,3,20200000005

Head of df_2021:

,YEAR,AGE,EDUC,ETHNIC,RACE,GENDER,SPHSERVICE,CMPSERVICE,OPISERVICE,RTCSERVICE,IJSSERVICE,MH1,MH2,MH3,SUB,MARSTAT,SMISED,SAP,EMPLOY,DETNLF,VETERAN,LIVARAG,NUMMHS,TRAUSTREFLG,ANXIETYFLG,ADHDFLG,CONDUCTFLG,DELIRDEMFLG,BIPOLARFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
0,2021,13,5,4,5,1,1,2,2,2,2,-9,-9,-9,-9,1,1,2,-9,-9,2,-9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6,3,20210000001
1,2021,7,-9,3,3,1,1,1,2,2,2,11,-9,-9,9,1,1,1,-9,-9,-9,3,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,6,3,20210000002
2,2021,12,-9,4,2,1,1,1,1,2,2,11,-9,-9,-9,1,1,1,-9,-9,-9,-9,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,6,3,20210000003
3,2021,14,-9,3,3,2,2,1,2,2,2,11,-9,-9,-9,1,-9,-9,-9,-9,-9,-9,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,6,3,20210000004
4,2021,3,3,4,5,1,1,1,2,2,2,2,3,-9,-9,1,2,2,-9,-9,-9,2,2,0,1,1,0,0,0,0,0,0,0,0,0,0,1,6,3,20210000005

Head of df_2022:

,YEAR,AGE,EDUC,ETHNIC,RACE,GENDER,SPHSERVICE,CMPSERVICE,OPISERVICE,RTCSERVICE,IJSSERVICE,MH1,MH2,MH3,SUB,MARSTAT,SMISED,SAP,EMPLOY,DETNLF,VETERAN,LIVARAG,NUMMHS,TRAUSTREFLG,ANXIETYFLG,ADHDFLG,CONDUCTFLG,DELIRDEMFLG,BIPOLARFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
0,2022,14,-9,3,3,2,2,1,2,2,2,11,-9,-9,-9,1,-9,-9,-9,-9,-9,-9,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,6,3,20220000001
1,2022,7,3,3,4,1,2,1,2,2,2,7,11,-9,-9,2,1,1,4,-9,2,2,2,0,0,0,0,0,0,1,0,0,0,1,0,0,1,6,3,20220000002
2,2022,8,3,3,-9,2,2,1,1,2,2,-9,-9,-9,-9,1,3,2,4,-9,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6,3,20220000003
3,2022,14,4,4,2,2,1,1,2,2,2,11,-9,-9,-9,4,1,2,5,1,2,3,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,6,3,20220000004
4,2022,3,-9,4,6,2,2,1,1,2,2,7,2,-9,-9,1,2,1,-9,-9,-9,-9,2,0,1,0,0,0,0,1,0,0,0,0,0,0,1,6,3,20220000005

### Concatenate all years into one dataframe

In [5]:
# Collect all DataFrames in a list
dfs = [globals()[f'df_{year}'] for year in range(2020, 2023) if f'df_{year}' in globals()]

# Concatenate them into a single DataFrame
df = pd.concat(dfs, ignore_index=True)

In [6]:
df.shape

(20423440, 40)

In [7]:
df.head()

,YEAR,AGE,EDUC,ETHNIC,RACE,GENDER,SPHSERVICE,CMPSERVICE,OPISERVICE,RTCSERVICE,IJSSERVICE,MH1,MH2,MH3,SUB,MARSTAT,SMISED,SAP,EMPLOY,DETNLF,VETERAN,LIVARAG,NUMMHS,TRAUSTREFLG,ANXIETYFLG,ADHDFLG,CONDUCTFLG,DELIRDEMFLG,BIPOLARFLG,DEPRESSFLG,ODDFLG,PDDFLG,PERSONFLG,SCHIZOFLG,ALCSUBFLG,OTHERDISFLG,STATEFIP,DIVISION,REGION,CASEID
0,2020,14,-9,4,3,1,1,1,1,2,2,5,11,-9,-9,1,1,1,-9,-9,-9,3,2,0,0,0,0,1,0,0,0,0,0,1,0,0,1,6,3,20200000001
1,2020,1,2,4,1,1,2,1,2,2,2,13,2,3,-9,1,2,2,-9,-9,-9,-9,3,0,1,1,0,0,0,0,0,0,0,0,0,1,1,6,3,20200000002
2,2020,3,3,4,6,2,2,1,2,1,2,1,2,-9,-9,-9,2,2,5,5,-9,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0,1,6,3,20200000003
3,2020,12,4,4,1,1,1,1,2,2,2,11,10,-9,5,-9,1,1,2,-9,-9,3,2,0,0,0,0,0,0,0,0,0,1,1,0,0,1,6,3,20200000004
4,2020,8,3,3,5,1,2,1,1,2,2,10,-9,-9,10,-9,1,1,1,-9,-9,3,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,6,3,20200000005

In [8]:
# Add underscore to CASEID and lowercase
df = df.rename(columns={'CASEID':'_caseid',})

In [9]:
# Add underscore to YEAR and lowercase
df = df.rename(columns={'YEAR':'_year',})

### Drop unnecessary columns

In [10]:
df = df.drop(columns=['EDUC',
                      'ETHNIC',
                      'SPHSERVICE',
                      'CMPSERVICE',
                      'OPISERVICE',
                      'RTCSERVICE',
                      'IJSSERVICE',
                      'NUMMHS',
                      'DIVISION',
                     ])

In [11]:
df.to_csv('../data/2020_to_2022.csv', index=False)

### Remapping of values and labels

In [12]:
# Mapping of values to labels for AGE
age_mapping = {
    1: '0-11 years',
    2: '12-14 years',
    3: '15-17 years',
    4: '18-20 years',
    5: '21-24 years',
    6: '25-29 years',
    7: '30-34 years',
    8: '35-39 years',
    9: '40-44 years',
    10: '45-49 years',
    11: '50-54 years',
    12: '55-59 years',
    13: '60-64 years',
    14: '65 years and older',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the AGE column
df['_age'] = df['AGE'].map(age_mapping)

# Remove AGE column
df = df.drop(columns=['AGE'])

In [13]:
# Mapping of values to labels
race_mapping = {
    1: 'American Indian/Alaska Native',
    2: 'Asian',
    3: 'Black or African American',
    4: 'Native Hawaiian or Other Pacific Islander',
    5: 'White',
    6: 'Some other race alone/two or more races',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the RACE column
df['_race'] = df['RACE'].map(race_mapping)

# Remove the original RACE column
df = df.drop(columns=['RACE'])

In [14]:
# Mapping of values to labels
gender_mapping = {
    1: 'Male',
    2: 'Female',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the GENDER column
df['_gender'] = df['GENDER'].map(gender_mapping)

# Remove the original GENDER column
df = df.drop(columns=['GENDER'])

In [15]:
# Mapping of values to labels
mh_mapping = {
    1: 'Trauma- and stressor-related disorders',
    2: 'Anxiety disorders',
    3: 'Attention deficit/hyperactivity disorder (ADHD)',
    4: 'Conduct disorders',
    5: 'Delirium/dementia disorders',
    6: 'Bipolar disorders',
    7: 'Depressive disorders',
    8: 'Oppositional defiant disorders',
    9: 'Pervasive developmental disorders',
    10: 'Personality disorders',
    11: 'Schizophrenia or other psychotic disorders',
    12: 'Alcohol or substance use disorders',
    13: 'Other disorders/conditions',
    -9: 'Missing/unknown/not collected/invalid/no or deferred diagnosis'
}

# Recode the MH1 column
df['_mh1'] = df['MH1'].map(mh_mapping)

# Recode the MH2 column
df['_mh2'] = df['MH2'].map(mh_mapping)

# Recode the MH3 column
df['_mh3'] = df['MH3'].map(mh_mapping)

# Remove the original MH1 column
df = df.drop(columns=['MH1', 'MH2', 'MH3'])

In [16]:
# Mapping of values to labels
sub_mapping = {
    1: 'Alcohol-induced disorder',
    2: 'Alcohol intoxication',
    3: 'Substance-induced disorder',
    4: 'Alcohol dependence',
    5: 'Cocaine dependence',
    6: 'Cannabis dependence',
    7: 'Opioid dependence',
    8: 'Other substance dependence',
    9: 'Alcohol abuse',
    10: 'Cocaine abuse',
    11: 'Cannabis abuse',
    12: 'Opioid abuse',
    13: 'Other substance related conditions',
    -9: 'Missing/unknown/not collected/invalid/no or deferred diagnosis'
}

# Recode the SUB column
df['_substance_use'] = df['SUB'].map(sub_mapping)

# Drop the original SUB column
df = df.drop(columns=['SUB'])

In [17]:
# Mapping of values to labels
marstat_mapping = {
    1: 'Never married',
    2: 'Now married',
    3: 'Separated',
    4: 'Divorced, widowed',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the MARSTAT column
df['_marital_status'] = df['MARSTAT'].map(marstat_mapping)

# Drop the original SUB column
df = df.drop(columns=['MARSTAT'])

In [18]:
# Mapping of values to labels
smised_mapping = {
    1: 'SMI',
    2: 'SED and/or at risk for SED',
    3: 'Not SMI/SSED',
    4: 'Divorced, widowed',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the SMISED column
df['_smi_sed'] = df['SMISED'].map(smised_mapping)

# Drop the original SUB column
df = df.drop(columns=['SMISED'])

In [19]:
# Mapping of values to labels
sap_mapping = {
    1: 'Yes',
    2: 'No',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the SAP column
df['_substance_abuse_problem'] = df['SAP'].map(sap_mapping)

# Drop the original SUB column
df = df.drop(columns=['SAP'])

In [20]:
# Mapping of values to labels
employment_mapping = {
    1: 'Full-time',
    2: 'Part-time',
    3: 'Employed full-time/part-time not differentiated',
    4: 'Unemployed',
    5: 'Not in labor force',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the EMPLOY column
df['_employment'] = df['EMPLOY'].map(employment_mapping)

# Drop the original EMPLOY column
df = df.drop(columns=['EMPLOY'])

In [21]:
# Mapping of values to labels
not_in_labor_force_mapping = {
    1: 'Retired, disabled',
    2: 'Student',
    3: 'Homemaker',
    4: 'Sheltered/non-competitive employment',
    5: 'Other',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the DETNLF column
df['_not_in_labor_force_detail'] = df['DETNLF'].map(not_in_labor_force_mapping)

# Drop the original DETNLF column
df = df.drop(columns=['DETNLF'])

In [22]:
# Mapping of values to labels
vet_mapping = {
    1: 'Yes',
    2: 'No',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the SAP column
df['_veteran_status'] = df['VETERAN'].map(vet_mapping)

# Drop the original SUB column
df = df.drop(columns=['VETERAN'])

In [23]:
# Mapping of values to labels
residential_status_mapping = {
    1: 'Experiencing Homelessness',
    2: 'Private residence',
    3: 'Other',
    -9: 'Missing/unknown/not collected/invalid'
}

# Recode the LIVARAG column
df['_residential_status'] = df['LIVARAG'].map(residential_status_mapping)

# Drop the original LIVARAG column
df = df.drop(columns=['LIVARAG'])

In [24]:
# Mapping of values to labels
disorder_mapping = {
    0: 'Disorder not reported',
    1: 'Disorder reported'
}

# Function to recode and drop the original column
def recode_and_drop_column(df, old_column, new_column, value_mapping):
    # Recode the old column based on the mapping
    df[new_column] = df[old_column].map(value_mapping)
    
    # Drop the old column
    df = df.drop(columns=[old_column])
    
    return df

In [25]:
df = recode_and_drop_column(df, 'TRAUSTREFLG', '_trauma_stressor_related_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'ANXIETYFLG', '_anxiety_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'ADHDFLG', '_attention_deficit_hyperactivity_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'CONDUCTFLG', '_conduct_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'DELIRDEMFLG', '_delirium_dementia_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'BIPOLARFLG', '_bipolar_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'DEPRESSFLG', '_depressive_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'ODDFLG', '_oppositional_defiant_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'PDDFLG', '_pervasive_developmental_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'PERSONFLG', '_personality_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'SCHIZOFLG', '_schizophrenia_other_pyschotic_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'ALCSUBFLG', '_alcohol_or_substance_abuse_disorder', disorder_mapping)
df = recode_and_drop_column(df, 'OTHERDISFLG', '_other_mental_disorder', disorder_mapping)

In [26]:
# Mapping of STATEFIP values to labels
state_mapping = {
    1: 'Alabama', 2: 'Alaska', 4: 'Arizona', 5: 'Arkansas', 6: 'California',
    8: 'Colorado', 9: 'Connecticut', 10: 'Delaware', 11: 'District of Columbia',
    12: 'Florida', 13: 'Georgia', 15: 'Hawaii', 16: 'Idaho', 17: 'Illinois',
    18: 'Indiana', 19: 'Iowa', 20: 'Kansas', 21: 'Kentucky', 22: 'Louisiana',
    24: 'Maryland', 25: 'Massachusetts', 26: 'Michigan', 27: 'Minnesota',
    28: 'Mississippi', 29: 'Missouri', 30: 'Montana', 31: 'Nebraska', 32: 'Nevada',
    33: 'New Hampshire', 34: 'New Jersey', 35: 'New Mexico', 36: 'New York',
    37: 'North Carolina', 38: 'North Dakota', 39: 'Ohio', 40: 'Oklahoma', 41: 'Oregon',
    42: 'Pennsylvania', 44: 'Rhode Island', 45: 'South Carolina', 46: 'South Dakota',
    47: 'Tennessee', 48: 'Texas', 49: 'Utah', 50: 'Vermont', 51: 'Virginia',
    53: 'Washington', 54: 'West Virginia', 55: 'Wisconsin', 56: 'Wyoming',
    72: 'Puerto Rico', 99: 'Other jurisdictions'
}

# Recode the STATEFIP column
df['_state'] = df['STATEFIP'].map(state_mapping)

# Drop the original LIVARAG column
df = df.drop(columns=['STATEFIP'])

In [27]:
# Mapping of REGION values to labels
region_mapping = {
    0: 'Other jurisdictions',
    1: 'Northeast',
    2: 'Midwest',
    3: 'South',
    4: 'West'
}

# Recode the REGION column
df['_region'] = df['REGION'].map(region_mapping)

# Drop the original REGION column
df = df.drop(columns=['REGION'])

In [28]:
df.head().T

,0,1,2,3,4
_year,2020,2020,2020,2020,2020
_caseid,20200000001,20200000002,20200000003,20200000004,20200000005
_age,65 years and older,0-11 years,15-17 years,55-59 years,35-39 years
_race,Black or African American,American Indian/Alaska Native,Some other race alone/two or more races,American Indian/Alaska Native,White
_gender,Male,Male,Female,Male,Male
_mh1,Delirium/dementia disorders,Other disorders/conditions,Trauma- and stressor-related disorders,Schizophrenia or other psychotic disorders,Personality disorders
_mh2,Schizophrenia or other psychotic disorders,Anxiety disorders,Anxiety disorders,Personality disorders,Missing/unknown/not collected/invalid/no or deferred diagnosis
_mh3,Missing/unknown/not collected/invalid/no or deferred diagnosis,Attention deficit/hyperactivity disorder (ADHD),Missing/unknown/not collected/invalid/no or deferred diagnosis,Missing/unknown/not collected/invalid/no or deferred diagnosis,Missing/unknown/not collected/invalid/no or deferred diagnosis
_substance_use,Missing/unknown/not collected/invalid/no or deferred diagnosis,Missing/unknown/not collected/invalid/no or deferred diagnosis,Missing/unknown/not collected/invalid/no or deferred diagnosis,Cocaine dependence,Cocaine abuse
_marital_status,Never married,Never married,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid
_smi_sed,SMI,SED and/or at risk for SED,SED and/or at risk for SED,SMI,SMI
_substance_abuse_problem,Yes,No,No,Yes,Yes
_employment,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid,Not in labor force,Part-time,Full-time
_not_in_labor_force_detail,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid,Other,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid
_veteran_status,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid,Missing/unknown/not collected/invalid
_residential_status,Other,Missing/unknown/not collected/invalid,Private residence,Other,Other
_trauma_stressor_related_disorder,Disorder not reported,Disorder not reported,Disorder reported,Disorder not reported,Disorder not reported
_anxiety_disorder,Disorder not reported,Disorder reported,Disorder reported,Disorder not reported,Disorder not reported
_attention_deficit_hyperactivity_disorder,Disorder not reported,Disorder reported,Disorder not reported,Disorder not reported,Disorder not reported
_conduct_disorder,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported
_delirium_dementia_disorder,Disorder reported,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported
_bipolar_disorder,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported
_depressive_disorder,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported
_oppositional_defiant_disorder,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported
_pervasive_developmental_disorder,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported
_personality_disorder,Disorder not reported,Disorder not reported,Disorder not reported,Disorder reported,Disorder reported
_schizophrenia_other_pyschotic_disorder,Disorder reported,Disorder not reported,Disorder not reported,Disorder reported,Disorder not reported
_alcohol_or_substance_abuse_disorder,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported,Disorder not reported
_other_mental_disorder,Disorder not reported,Disorder reported,Disorder not reported,Disorder not reported,Disorder not reported
_state,Alabama,Alabama,Alabama,Alabama,Alabama
_region,South,South,South,South,South

### Remove underscore prefixes

In [29]:
# Remove the first underscore from all column names
df.columns = df.columns.str.lstrip('_')

## Save to parquet

In [30]:
# Save the DataFrame to a Parquet file
df.to_parquet('../data/recoded_2020_2022.parquet', engine='pyarrow')

In [31]:
# Read the Parquet file back into a DataFrame
# df_from_parquet = pd.read_parquet('output_file.parquet', engine='pyarrow')  # or use engine='fastparquet'